version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/todo_api
    command: >
      sh -c "python manage.py migrate &&
             gunicorn todo_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend/todo_api:/app/todo_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
