apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: todo-app
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index todo.html;
        try_files $uri $uri/ =404;
      }
    }
