name: Build, Push and Deploy

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/todo_api
        file: ./backend/todo_api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/full-stack-to-do-list-application:backend-latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/full-stack-to-do-list-application:frontend-latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
        -H "Authorization: Bearer ${RENDER_API_KEY}" \
        -H "Content-Type: application/json" \
        -d '{}'
